; ==== pjsip.endpoint.conf ====
[gw1rn9]
type=endpoint
transport=0.0.0.0-tls
context=from-gsm-gateway
disallow=all
allow=opus,alaw
aors=gw1rn9
send_connected_line=no
rtp_keepalive=0
language=ru
auth=gw1rn9
user_eq_phone=no
t38_udptl=no
t38_udptl_ec=none
fax_detect=no
trust_id_inbound=no
t38_udptl_nat=no
direct_media=no
rewrite_contact=yes
media_encryption=sdes
rtp_symmetric=yes
dtmf_mode=rfc4733

; ==== pjsip.aor.conf ====
[gw1rn9]
type=aor
qualify_frequency=30
max_contacts=1

; ==== pjsip.auth.conf ====
[gw1rn9]
type=auth
auth_type=userpass
password=REDACTED
username=gw1rn9

; ==== pjsip.identify.conf ====
; ==== trunk dial strings (extensions_additional.conf [globals]) ====
OUT_1 = PJSIP
OUT_1_SUFFIX = @gw1rn9
OUT_2 = AMP:Local/1011*$OUTNUM$@gsm-out/n
OUT_3 = AMP:Local/1012*$OUTNUM$@gsm-out/n
; ==== outbound route order ====
include => outbound-allroutes-custom
include => outrt-1 ; GSM-SIM1-forced
include => outrt-2 ; GSM-SIM2-forced
include => outrt-3 ; GSM-default-2001
; ==== outbound route dial patterns ====
exten => _**.
exten => _*1+7XXXXXXXXXX
exten => _*18XXXXXXXXXX
exten => _*2+7XXXXXXXXXX
exten => _*28XXXXXXXXXX
exten => _*54.
exten => _*55.
exten => _+7XXXXXXXXXX
exten => _+7XXXXXXXXXX/2001
exten => _***80.
exten => _*80.
exten => _8XXXXXXXXXX
exten => _8XXXXXXXXXX/2001
